### PR TITLE
Change project icon

### PR DESCRIPTION
**Pull request by Geometror**
I know this has near zero priority right now, but I made this for a personal benchmark project for fun.
This icon might be a bit clearer/more distinguishable from the default project icon while it still contains those colors, so I figured that before it goes to waste I just open a PR here. Let me know what you think :)

icon

Technical info: It's a PNG since the SVG uses SVG 2 mesh gradients which are not supported yet by ThorVG.

### CODE REVIEW

**Comment by Chubercik** [comment]
Is there a 256×256 version perhaps?
Doubt it matters much but downsampling the icon 4 times seems feels like a regression.

**Comment by Geometror** [comment]
I could export a high-res version, but 128×128 pixels is the default for a project icon and I honestly can't think of a situation where the high-res version would be beneficial.

**Comment by Geometror** [comment]
Changed the resolution to 256x256.

**Comment by Calinou** [comment]
> I could export a high-res version, but 128×128 pixels is the default for a project icon and I honestly can't think of a situation where the high-res version would be beneficial.

Alt-tab dialogs on some OSes (here, KDE Plasma) can benefit from icons larger than 128×128:

image

The displayed size above seems to be around 160×160, but it can be greater on hiDPI displays.

**Review by Calinou — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
