### PR TITLE
add convex hull 3d benchmark

### PR DESCRIPTION
**Pull request by franciscod**

### CODE REVIEW

**Review by Calinou — COMMENTED** [review]
Tested locally, it works as expected.

For reference, I get these results on a release build with an i9-13900K:

image

Is it expected that there's little difference between any of these tests in terms of runtime?

**Comment by franciscod** [comment]
Results on a Mac Mini (M2):

image

Godot Engine v4.2.1.stable.mono.official.b09f793f5

**Comment by franciscod** [comment]
And here are the results from the laptop on which I originally calibrated the benchmark:

```
"system":{"cpu_architecture":"x86_64","cpu_count":4,
"cpu_name":"Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz",
"gpu_name":"Intel(R) HD Graphics 520 (SKL GT2)","gpu_vendor":"Intel","os":"Linux"}
```

AC plugged in (performance mode):
image

Battery (power saving mode):
image

(also Godot Engine v4.2.1.stable.mono.official.b09f793f5)

**Review by Calinou — APPROVED** [review]
Let's go with these benchmarks for now and see if they need to be improved if there's lots of variance on the benchmarks server.

Thanks!

**Comment by franciscod** [comment]
I just noticed that these benchmark weren't working. Follow-up PR soon!

**Pull request merged**
