### PR TITLE
Add more label benchmarks

### PR DESCRIPTION
**Pull request by OverloadedOrama**
Adds the following benchmarks from #36:

- 🟥CPU🟥 RichTextLabel long text shaping: Display a RichTextLabel with [100+ paragraphs of Lorem Ipsum](https://www.lipsum.com/)
- 🟥CPU🟥 Text Resizing : Create a complex paragraph (loren ipsum) in a Label. Make a script that resizes it evey frame so it has to re-fit the text.

- ~~🟥CPU🟥 Container sorting: Make a BoxContainer with 1000 Control children and call queue_sort() for 1000 frames in a row~~
- ~~🟥CPU🟥 Container resizing : Create a random set of containers up to 20 levels. Every frame resize the parent container, measure CPU.~~
EDIT: Removed the container benchmarks as recommended in https://github.com/godotengine/godot-benchmarks/pull/71#issuecomment-2159054345.

Seems like ` 🟥CPU🟥 Text Rendering : Create a label with a huge text (lorem impsum) with a tiny font size that fills the screen. Measure performance` was already implemented in label.gd.

I also moved label.gd from the rendering folder to a new gui folder for better organizing.

One thing I'm not sure of, however, is that the container sorting benchmark asks for 1000 frames in a row, which to my knowledge is not currently possible to test because the benchmarks are hard-coded to 5 seconds. Should I make further changes to the code so that each benchmark can have the ability to change the time they take?

<details>
<summary>Results on my laptop</summary>

{
	"benchmarks": [
		{
			"category": "Gui > Container",
			"name": "Container Resizing",
			"results": {
				"render_cpu": 0.009149,
				"time": 0.239
			}
		},
		{
			"category": "Gui > Container",
			"name": "Container Sorting",
			"results": {
				"render_cpu": 0.03911,
				"time": 3.84
			}
		},
		{
			"category": "Gui > Label",
			"name": "Label",
			"results": {
				"render_cpu": 0.9346,
				"render_gpu": 0.4779,
				"time": 0.112
			}
		},
		{
			"category": "Gui > Label",
			"name": "Label Autowrap Arbitrary",
			"results": {
				"render_cpu": 0.9912,
				"render_gpu": 0.4784,
				"time": 0.119
			}
		},
		{
			"category": "Gui > Label",
			"name": "Label Autowrap Smart",
			"results": {
				"render_cpu": 1.017,
				"render_gpu": 0.4792,
				"time": 0.151
			}
		},
		{
			"category": "Gui > Label",
			"name": "Label Autowrap Word",
			"results": {
				"render_cpu": 1.033,
				"render_gpu": 0.4797,
				"time": 0.143
			}
		},
		{
			"category": "Gui > Label",
			"name": "Label Resize",
			"results": {
				"render_cpu": 1.06,
				"render_gpu": 1.417,
				"time": 0.133
			}
		},
		{
			"category": "Gui > Label",
			"name": "Rich Text Label",
			"results": {
				"render_cpu": 2.252,
				"render_gpu": 0.7583,
				"time": 0.487
			}
		}
	],
	"engine": {
		"version": "v4.3.beta1.official",
		"version_hash": "a4f2ea91a1bd18f70a43ff4c1377db49b56bc3f0"
	},
	"system": {
		"cpu_architecture": "x86_64",
		"cpu_count": 12,
		"cpu_name": "AMD Ryzen 5 6600H with Radeon Graphics",
		"os": "Linux"
	}
}

</details>

### CODE REVIEW

**Review by Calinou — APPROVED** [review]
Tested locally, it works as expected.

**Comment by Calinou** [comment]
> One thing I'm not sure of, however, is that the container sorting benchmark asks for 1000 frames in a row, which to my knowledge is not currently possible to test because the benchmarks are hard-coded to 5 seconds. Should I make further changes to the code so that each benchmark can have the ability to change the time they take?

V-Sync is disabled in the benchmarks project, so it's possible to render more than 60 FPS if the CPU/GPU can keep up.

Benchmarks that have Render CPU/GPU reporting disabled have no time limit, so maybe you could disable it for the container benchmarks.

**Comment by OverloadedOrama** [comment]
> Benchmarks that have Render CPU/GPU reporting disabled have no time limit, so maybe you could disable it for the container benchmarks.

Do you mean the `test_render_cpu` and `test_render_gpu` variables? Setting them to false doesn't seem to change anything rather than the CPU/GPU time being reported at the end of the benchmark, the benchmark still takes 5 seconds. The 5 seconds seem to be hard-coded in manager.gd's `run_test()` method. If I understand the code correctly, every benchmark that returns a node, takes 5 seconds. I think we may need to change this time limit and make it configurable, as some benchmarks in the list require more than 5 seconds, for example the physics benchmarks.

**Comment by Calinou** [comment]
I don't know either way, as the time reported by the container sorting benchmark is meaningless due to (what I assume is) https://github.com/godotengine/godot/issues/20623. It may be better to remove this benchmark for now as it'd be misleading otherwise.

**Comment by OverloadedOrama** [comment]
All right, I removed the container benchmarks.

**Review by Calinou — APPROVED** [review]
Thanks!

**Pull request merged**
